settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 0
  host: ""
schema:
- name: backend
  path: .
  commands:
    fmt:
      status: true
    install:
      status: true
    run:
      status: true
  watcher:
    scripts:
    - type: before
      command: taskkill /im backend.exe /F
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
    - public